version: '2.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=soap
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    ports:
      - "33061:3306"
  redis:
    image: redis
    restart: always
    volumes:
      - ./docker-data/redis:/data
    ports:
      - "63791:6379"
