version: '2.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-data/mysql:/var/lib/mysql:rw
    ports:
      - "33061:3306"
  redis:
    image: redis
    restart: always
    volumes:
      - ./docker-data/redis:/data:rw
    ports:
      - "63791:6379"
