import {MigrationInterface, QueryRunner} from "typeorm";

export class AddOauth1568875380441 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `collection` DROP FOREIGN KEY `FK_9a4e12cc34d9cd097d07567f532`", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` DROP FOREIGN KEY `FK_f1d981b0218e050c99f5bd2d31a`", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` DROP FOREIGN KEY `FK_8cb5c5e1d5330f16598c464b901`", undefined);
        await queryRunner.query("CREATE TABLE `user_credentials` (`id` varchar(255) NOT NULL, `type` enum ('GITHUB', 'GOOGLE') NOT NULL, `info` text NULL, `userId` int NULL, `userUsername` varchar(40) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` DROP FOREIGN KEY `FK_b1762400030ae028f052ef8e297`", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `picture` DROP FOREIGN KEY `FK_b64f081c1b4d709730c7d7dd1c0`", undefined);
        await queryRunner.query("ALTER TABLE `picture` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `picture` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` DROP FOREIGN KEY `FK_b87d39671a9ae3eacbe7285bc1e`", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `collection` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `file` DROP FOREIGN KEY `FK_04dc431627294668dbe5ae00332`", undefined);
        await queryRunner.query("ALTER TABLE `file` DROP FOREIGN KEY `FK_fa1a667374cc4203897f33e2e23`", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP FOREIGN KEY `FK_8981f3185dbb71c49f2fdf18ef2`", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` DROP FOREIGN KEY `FK_dad53ffe7f56e2da3a5fc5d5f7b`", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` DROP FOREIGN KEY `FK_15283a167b950b19c66e6dad1a6`", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `id` int NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP PRIMARY KEY", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD PRIMARY KEY (`id`)", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `username`", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `username` varchar(40) NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `username` `id` int NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP PRIMARY KEY", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD PRIMARY KEY (`id`, `username`)", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `username` varchar(40) NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `signupType` `signupType` enum ('EMAIL', 'GITHUB', 'GOOGLE') NOT NULL DEFAULT 'EMAIL'", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `email` `email` varchar(255) NOT NULL DEFAULT ''", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `hash` `hash` varchar(255) NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `salt` `salt` varchar(255) NULL", undefined);
        await queryRunner.query("DROP INDEX `IDX_dad53ffe7f56e2da3a5fc5d5f7` ON `notification_subscribers_user`", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `publisherUsername`", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `publisherUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `file` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD `userUsername` varchar(40) NULL", undefined);
        await queryRunner.query("ALTER TABLE `file` DROP COLUMN `pictureUsername`", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD `pictureUsername` varchar(40) NULL", undefined);
        await queryRunner.query("CREATE INDEX `IDX_dad53ffe7f56e2da3a5fc5d5f7` ON `notification_subscribers_user` (`userId`, `userUsername`)", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` ADD CONSTRAINT `FK_b1762400030ae028f052ef8e297` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `picture` ADD CONSTRAINT `FK_b64f081c1b4d709730c7d7dd1c0` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` ADD CONSTRAINT `FK_b87d39671a9ae3eacbe7285bc1e` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `collection` ADD CONSTRAINT `FK_9a4e12cc34d9cd097d07567f532` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `user_credentials` ADD CONSTRAINT `FK_701a5a1d271d862bebb36f13d8d` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` ADD CONSTRAINT `FK_dad53ffe7f56e2da3a5fc5d5f7b` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD CONSTRAINT `FK_8981f3185dbb71c49f2fdf18ef2` FOREIGN KEY (`publisherId`, `publisherUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` ADD CONSTRAINT `FK_f1d981b0218e050c99f5bd2d31a` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` ADD CONSTRAINT `FK_8cb5c5e1d5330f16598c464b901` FOREIGN KEY (`clientId`) REFERENCES `client`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` ADD CONSTRAINT `FK_15283a167b950b19c66e6dad1a6` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD CONSTRAINT `FK_04dc431627294668dbe5ae00332` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD CONSTRAINT `FK_fa1a667374cc4203897f33e2e23` FOREIGN KEY (`pictureId`, `pictureUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `file` DROP FOREIGN KEY `FK_fa1a667374cc4203897f33e2e23`", undefined);
        await queryRunner.query("ALTER TABLE `file` DROP FOREIGN KEY `FK_04dc431627294668dbe5ae00332`", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` DROP FOREIGN KEY `FK_15283a167b950b19c66e6dad1a6`", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` DROP FOREIGN KEY `FK_8cb5c5e1d5330f16598c464b901`", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` DROP FOREIGN KEY `FK_f1d981b0218e050c99f5bd2d31a`", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP FOREIGN KEY `FK_8981f3185dbb71c49f2fdf18ef2`", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` DROP FOREIGN KEY `FK_dad53ffe7f56e2da3a5fc5d5f7b`", undefined);
        await queryRunner.query("ALTER TABLE `user_credentials` DROP FOREIGN KEY `FK_701a5a1d271d862bebb36f13d8d`", undefined);
        await queryRunner.query("ALTER TABLE `collection` DROP FOREIGN KEY `FK_9a4e12cc34d9cd097d07567f532`", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` DROP FOREIGN KEY `FK_b87d39671a9ae3eacbe7285bc1e`", undefined);
        await queryRunner.query("ALTER TABLE `picture` DROP FOREIGN KEY `FK_b64f081c1b4d709730c7d7dd1c0`", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` DROP FOREIGN KEY `FK_b1762400030ae028f052ef8e297`", undefined);
        await queryRunner.query("DROP INDEX `IDX_dad53ffe7f56e2da3a5fc5d5f7` ON `notification_subscribers_user`", undefined);
        await queryRunner.query("ALTER TABLE `file` DROP COLUMN `pictureUsername`", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD `pictureUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `file` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `notification` DROP COLUMN `publisherUsername`", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD `publisherUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("CREATE INDEX `IDX_dad53ffe7f56e2da3a5fc5d5f7` ON `notification_subscribers_user` (`userId`, `userUsername`)", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `salt` `salt` varchar(255) NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `hash` `hash` varchar(255) NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `email` `email` varchar(255) NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `signupType` `signupType` enum ('EMAIL') NOT NULL DEFAULT 'EMAIL'", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `username` `id` int NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP PRIMARY KEY", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD PRIMARY KEY (`id`)", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `username` varchar(40) NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `username`", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD `username` varchar(15) NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `id` int NOT NULL", undefined);
        await queryRunner.query("ALTER TABLE `user` DROP PRIMARY KEY", undefined);
        await queryRunner.query("ALTER TABLE `user` ADD PRIMARY KEY (`id`, `username`)", undefined);
        await queryRunner.query("ALTER TABLE `user` CHANGE `id` `id` int NOT NULL AUTO_INCREMENT", undefined);
        await queryRunner.query("ALTER TABLE `picture_comment` ADD CONSTRAINT `FK_15283a167b950b19c66e6dad1a6` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `notification_subscribers_user` ADD CONSTRAINT `FK_dad53ffe7f56e2da3a5fc5d5f7b` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `notification` ADD CONSTRAINT `FK_8981f3185dbb71c49f2fdf18ef2` FOREIGN KEY (`publisherId`, `publisherUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD CONSTRAINT `FK_fa1a667374cc4203897f33e2e23` FOREIGN KEY (`pictureId`, `pictureUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `file` ADD CONSTRAINT `FK_04dc431627294668dbe5ae00332` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `collection` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `collection` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `collection_picture` ADD CONSTRAINT `FK_b87d39671a9ae3eacbe7285bc1e` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE CASCADE ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `picture` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `picture` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `picture` ADD CONSTRAINT `FK_b64f081c1b4d709730c7d7dd1c0` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` DROP COLUMN `userUsername`", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` ADD `userUsername` varchar(15) NULL", undefined);
        await queryRunner.query("ALTER TABLE `picture_user_activity` ADD CONSTRAINT `FK_b1762400030ae028f052ef8e297` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("DROP TABLE `user_credentials`", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` ADD CONSTRAINT `FK_8cb5c5e1d5330f16598c464b901` FOREIGN KEY (`clientId`) REFERENCES `client`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `accessToken` ADD CONSTRAINT `FK_f1d981b0218e050c99f5bd2d31a` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
        await queryRunner.query("ALTER TABLE `collection` ADD CONSTRAINT `FK_9a4e12cc34d9cd097d07567f532` FOREIGN KEY (`userId`, `userUsername`) REFERENCES `user`(`id`,`username`) ON DELETE NO ACTION ON UPDATE NO ACTION", undefined);
    }

}
